# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pgLogin = QtWidgets.QWidget()
        self.pgLogin.setObjectName("pgLogin")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pgLogin)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._inicial = QtWidgets.QFrame(self.pgLogin)
        self._inicial.setMinimumSize(QtCore.QSize(200, 80))
        self._inicial.setMaximumSize(QtCore.QSize(200, 80))
        self._inicial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._inicial.setFrameShadow(QtWidgets.QFrame.Raised)
        self._inicial.setObjectName("_inicial")
        self.gridLayout_2 = QtWidgets.QGridLayout(self._inicial)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputNick = QtWidgets.QLineEdit(self._inicial)
        self.inputNick.setMinimumSize(QtCore.QSize(180, 25))
        self.inputNick.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        self.inputNick.setFont(font)
        self.inputNick.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputNick.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 2px solid black;\n"
"    color: black;\n"
"    background: white;\n"
"}\n"
"")
        self.inputNick.setMaxLength(20)
        self.inputNick.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNick.setObjectName("inputNick")
        self.gridLayout_2.addWidget(self.inputNick, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.btnEntrar = QtWidgets.QPushButton(self._inicial)
        self.btnEntrar.setMinimumSize(QtCore.QSize(80, 25))
        self.btnEntrar.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.btnEntrar.setFont(font)
        self.btnEntrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEntrar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnEntrar.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    border: 2px solid black;\n"
"    color: black;\n"
"    background: white;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: black\n"
"}")
        self.btnEntrar.setObjectName("btnEntrar")
        self.gridLayout_2.addWidget(self.btnEntrar, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self._inicial, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgLogin)
        self.pgChat = QtWidgets.QWidget()
        self.pgChat.setStyleSheet("")
        self.pgChat.setObjectName("pgChat")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pgChat)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnEnviar = QtWidgets.QPushButton(self.pgChat)
        self.btnEnviar.setMinimumSize(QtCore.QSize(65, 25))
        self.btnEnviar.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnviar.setFont(font)
        self.btnEnviar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEnviar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnEnviar.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    border: 2px solid black;\n"
"    color: black;\n"
"    background: white;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background: gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: black\n"
"}")
        self.btnEnviar.setObjectName("btnEnviar")
        self.gridLayout_4.addWidget(self.btnEnviar, 1, 1, 1, 1)
        self.inputMsg = QtWidgets.QLineEdit(self.pgChat)
        self.inputMsg.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        self.inputMsg.setFont(font)
        self.inputMsg.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputMsg.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    border: 2px solid black;\n"
"    color: black;\n"
"    background: white;\n"
"}\n"
"")
        self.inputMsg.setClearButtonEnabled(True)
        self.inputMsg.setObjectName("inputMsg")
        self.gridLayout_4.addWidget(self.inputMsg, 1, 0, 1, 1)
        self.listChat = QtWidgets.QListWidget(self.pgChat)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(11)
        self.listChat.setFont(font)
        self.listChat.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.listChat.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.listChat.setAutoFillBackground(True)
        self.listChat.setStyleSheet("")
        self.listChat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listChat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listChat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listChat.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listChat.setAlternatingRowColors(False)
        self.listChat.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listChat.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listChat.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listChat.setMovement(QtWidgets.QListView.Static)
        self.listChat.setFlow(QtWidgets.QListView.TopToBottom)
        self.listChat.setProperty("isWrapping", False)
        self.listChat.setResizeMode(QtWidgets.QListView.Fixed)
        self.listChat.setLayoutMode(QtWidgets.QListView.Batched)
        self.listChat.setViewMode(QtWidgets.QListView.ListMode)
        self.listChat.setUniformItemSizes(False)
        self.listChat.setBatchSize(1000)
        self.listChat.setWordWrap(True)
        self.listChat.setSelectionRectVisible(True)
        self.listChat.setObjectName("listChat")
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listChat.addItem(item)
        self.gridLayout_4.addWidget(self.listChat, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.pgChat)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebChat"))
        self.inputNick.setPlaceholderText(_translate("MainWindow", "Digite seu apelido!"))
        self.btnEntrar.setText(_translate("MainWindow", "Entrar"))
        self.btnEnviar.setText(_translate("MainWindow", "Enviar"))
        self.inputMsg.setPlaceholderText(_translate("MainWindow", "Sua mensagem:"))
        __sortingEnabled = self.listChat.isSortingEnabled()
        self.listChat.setSortingEnabled(False)
        item = self.listChat.item(0)
        item.setText(_translate("MainWindow", "testejauisduhasuhduhasdh ahsudhuahsduhahsud uahsudhuahshduhad hausdhuashdhauhsudhu ahsduhhasuhduhas haushduaushd aushduhasuhdu uahsudhuahsd"))
        item = self.listChat.item(1)
        item.setText(_translate("MainWindow", "testejauisduhasuhduhasdh ahsudhuahsduhahsud uahsudhuahshduhad hausdhuashdhauhsudhu ahsduhhasuhduhas haushduaushd aushduhasuhdu uahsudhuahsd"))
        item = self.listChat.item(2)
        item.setText(_translate("MainWindow", "hasudhuahsduhas aushduahsduahsdu ahsduhaushduhashd uahsudhahsdhu"))
        item = self.listChat.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(10)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listChat.item(11)
        item.setText(_translate("MainWindow", "New Item"))
        self.listChat.setSortingEnabled(__sortingEnabled)
